### ISSUE TITLE
Failing rules

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther-analysis#128]
Trying to deploy latest rules I am getting this:

```
Failed Tests Summary
	AWS.S3.Bucket.ActionRestrictions
		['Bucket Does Not Restrict Any Actions Expanded']
```

**Comment by nhakmiller** [comment]
A dependency updated, which broke the rule.

We've had this exact same test on this same rule broken by this same dependency update in the past, so I'm just going to remove the test. The rest of the test logic should really be sufficient, and because we can't dynamically generate the test cases in python this rule will just break every few months or so whenever AWS adds a new s3 permission. Closed by #129.
