### ISSUE TITLE
Consider adding `requestParameters` to `aws_rule_context()` helper

### ISSUE THREAD

**Issue by pbnj-dragon** [panther-labs/panther-analysis#1401]
## Problem

When an alert from an AWS detection rule is sent to a destination, the alert context does not include `requestParameters`, which contains critical details relevant to the AWS alert and subsequent incident response.

## Proposed Enhancement

The `requestParameters` can be added to the [`aws_rule_context()` helper](https://github.com/panther-labs/panther-analysis/blob/03ed81c66e4fd01edd8fdea3e44f8ef62347adbc/global_helpers/panther_aws_helpers.py#L32-L41) helper function, like:

```diff
def aws_rule_context(event: dict):
    return {
        "eventName": event.get("eventName", "<MISSING_EVENT_NAME>"),
        "eventSource": event.get("eventSource", "<MISSING_ACCOUNT_ID>"),
        "awsRegion": event.get("awsRegion", "<MISSING_AWS_REGION>"),
        "recipientAccountId": event.get("recipientAccountId", "<MISSING_ACCOUNT_ID>"),
+       "requestParameters": event.get("requestParameters", "<MISSING_REQUEST_PARAMETERS>"),
        "sourceIPAddress": event.get("sourceIPAddress", "<MISSING_SOURCE_IP>"),
        "userAgent": event.get("userAgent", "<MISSING_USER_AGENT>"),
        "userIdentity": event.get("userIdentity", "<MISSING_USER_IDENTITY>"),
    }
```

## Workaround

The workaround would be to clone the managed rule, just to extend the `alert_context()`, like:

```diff
def alert_context(event):
-    return aws_rule_context(event)
+    return aws_rule_context(event) | {"requestParameters": event.get("requestParameters", "<MISSING_REQUEST_PARAMETERS>")}
```

But this approach has a few notable downsides:

1. Lose out when/if Panther-managed AWS detections are updated in the future
2. Duplicate all Panther-managed detections just to add a JSON key/value (high effort for little value)

Not sure if there is another workaround available that achieves the desired outcome without these downsides.

Happy to submit a Pull Request if the proposed solution is acceptable.

**Comment by arielkr256** [comment]
Hi @pbnj-dragon thanks for your patience on this one!  Although Panther's alert context can handle a large number of characters ([204800](https://help.panther.com/articles/6386481209-why-am-i-receiving-an-alert-context-size-bigger-than-maximum-error-in-panther)), most of our alert destinations have a much smaller API payload limit.  Since `requestParameters` can be pretty big (more than 10000 characters in my testing) we don't want to risk breaking alert delivery for customers who are using alert destinations with smaller payload sizes.

The good news is that the workaround you've described here is exactly how `alert_context` functions can be extended in PyPanther, and PyPanther will make it much easier to apply this type of change in bulk across your ruleset.
